name: Test Build

on:
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test build AMD64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: test:amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test build ARM64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: false
          tags: test:arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max